fix: versioning
Problem 1:
TypeError: Cannot read properties of undefined (reading 'getInitialProps')

Solution:
Deleted node_modules and ran npm install.

Problem 2:
Error: GraphQL Error (Code: 400): {"response":{"status":400,"headers":{}},"request":{"query":"\n        query GetPostDetails()

Solution:
Remove parens from GetPostDetails since GraphQL queries do not use parentheses unless passing args